<h1 class="page-header">Sample Heading</h1>
					
<p style="text-align: justify;">Your portfolio should include a close textual analysis: an essay in which you analyze closely a short work of literature (e.g., a sonnet) or an excerpt from a longer work. Your required 3000-level survey courses will include the option of writing this kind of assignment. A close textual analysis (also known as a close reading or Explication de texte) is a finely detailed, very specific interpretation of a short poem or short selected passage from a longer work, showing how the details of the textthe nuances of language, allusions, images and/or rhetorical figures (symbols, metaphors, etc.), the fictional situation, narrative techniquerelate to the central themes of the poem, story, or novel. This essay should demonstrate your ability to read sensitively, deliberately and carefully and to use critical terminology appropriately.

Your essay should be at least 3 double-spaced pages ( 750-1000 words) long. It should explore a poem or part of a poem of no more than 50 lines or a passage of prose (e.g., an excerpt from a short story, novel, play, etc.) of no more than 2 pages.

Your essay should interpret the text in depth and detail, paying close attention to the words on the page and giving your sense of what they mean and why they are significant. The essay should point out specific themes, character traits, ideas, images, concerns, stylistic features, etc. that you find important. It should pay some attention to expression and rhetorical strategy as well as to content. In other words, a close textual analysis either looks closely at a very short work in its entirety, or at a specific scene or moment in a longer work in order to make an argument about how a specific part of the poem or narrative contributes and relates to the whole. You must decide what total effect the writer achieves in a selected poem or passage and support your argument with quotes from the text. The argument you make should be about how the text you've chosen works (its internal functions, dynamics, and structures). It should not use the text to argue about an external generality (e.g. about the way life is) or an internal generality (e.g. about the nature of a certain character), nor should it use the text to "explain" the the historical context.

Close reading is used by many kinds of critics, from New Critical formalists to structuralists, deconstructionists, and members of various social, political, historical and reader-response schools. For a wide-ranging study of various methodologies that employ careful attention to the text, see Frank Lentricchia and Andrew Dubois, eds., Close Reading: The Reader (Durham: Duke Univ. Press, 2003).</p>
				
